// Code generated by MockGen. DO NOT EDIT.
// Source: internal/binance/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/binance/interface.go -destination=internal/binance/mock_client.go -package=binance
//

// Package binance is a generated GoMock package.
package binance

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBinanceClient is a mock of BinanceClient interface.
type MockBinanceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBinanceClientMockRecorder
	isgomock struct{}
}

// MockBinanceClientMockRecorder is the mock recorder for MockBinanceClient.
type MockBinanceClientMockRecorder struct {
	mock *MockBinanceClient
}

// NewMockBinanceClient creates a new mock instance.
func NewMockBinanceClient(ctrl *gomock.Controller) *MockBinanceClient {
	mock := &MockBinanceClient{ctrl: ctrl}
	mock.recorder = &MockBinanceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinanceClient) EXPECT() *MockBinanceClientMockRecorder {
	return m.recorder
}

// CreateMarketOrder mocks base method.
func (m *MockBinanceClient) CreateMarketOrder(ctx context.Context, symbol string, quantity float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMarketOrder", ctx, symbol, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMarketOrder indicates an expected call of CreateMarketOrder.
func (mr *MockBinanceClientMockRecorder) CreateMarketOrder(ctx, symbol, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMarketOrder", reflect.TypeOf((*MockBinanceClient)(nil).CreateMarketOrder), ctx, symbol, quantity)
}

// GetBalance mocks base method.
func (m *MockBinanceClient) GetBalance(ctx context.Context, asset string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, asset)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBinanceClientMockRecorder) GetBalance(ctx, asset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBinanceClient)(nil).GetBalance), ctx, asset)
}
